name: env_home_app
channels:
  - conda-forge
dependencies:
  - ipykernel=6.15.2
  - python=3.10
  - streamlit=1.23.0
  - pandas=1.5.3
  - plotly=5.13.0
  - altair=4.2.2
  - pydeck=0.8.0
  - protobuf=3.19.6
  - pip
  - pip:
     - pyrebase4 == 4.6.0
  
